#
# THIS GENERATES RegisterCapabilities.nsh BASED ON THE
# fileformats.db DATABASE.
#

# checking manually, these are the file endings that are actually ENABLED on Windows, excluding some that are to specialized for PhotoQt to be the default (e.g., videos, archives, ...)
FORMATS_AVAILABLE = ["aai", "ai", "apng", "ari", "avif", "avifs", "avs", "dng", "pdd", "psd", "psb", "psdt", "pix", "als", "alias", "ani", "qtk", "bmp", "dib", "cals", "cal", "ras", "cur", "crw", "crr", "cr2", "cr3", "cs1", "bay", "cine", "cb7", "cbr", "cbt", "cbz", "cube", "sixel", "dcm", "dic", "dpx", "dds", "cut", "pal", "dxo", "pes", "erf", "g3", "fits", "fts", "fit", "fl32", "raf", "gif", "xcf", "gpr", "rgbe", "hdr", "rad", "heif", "heic", "3fr", "fff", "ftx", "iff", "lbm", "pgx", "jfif", "jng", "jxl", "jxr", "hdp", "wdp", "jpeg", "jpg", "jpe", "jif", "viff", "xv", "dcr", "kdc", "drf", "k25", "dcs", "dc2", "kc2", "kra", "rgf", "mos", "raw", "rwl", "pxn", "mat", "mng", "mtv", "mpc", "mvg", "miff", "mef", "mfw", "ico", "mdc", "dfont", "nef", "nrw", "bmq", "obm", "orf", "ori", "otb", "exr", "ora", "otf", "ttf", "ttc", "pbm", "pcx", "art", "pgm", "pxr", "png", "ppm", "pnm", "tim", "sai", "pdb", "palm", "rw2", "pef", "ptx", "picon", "cap", "eip", "liq", "iiq", "pcd", "pcds", "pam", "pfm", "phm", "pfb", "pfm", "pfa", "ptif", "pict", "pct", "qoi", "r3d", "rwz", "rdc", "rgba", "rgb", "sgi", "bw", "sun", "ras", "sr", "im1", "im24", "im32", "im8", "rast", "rs", "scr", "svg", "svgz", "srw", "sct", "ch", "sfw", "pwp", "x3f", "sti", "hrz", "pic", "srf", "mrw", "sr2", "arq", "arw", "tga", "icb", "vda", "vst", "tiff", "tif", "rle", "vicar", "vtf", "webp", "rla", "wmf", "wbmp", "wpg", "xbm", "bm", "xpm", "pm", "dcx", "ff"]

import os

recorded = []

FINAL_CONT = """;
; DO NOT EDIT THIS FILE!
; THIS FILE IS AUTO GENERATED BY RegisterCapabilities.py AND WILL
; LIKELY BE OVERWRITTEN AT SOME POINT!
;
SetRegView 64

; Register PhotoQt as default application
WriteRegStr ShCtx "Software\\RegisteredApplications" "PhotoQt" "Software\\PhotoQt\\Capabilities"

WriteRegStr ShCtx "Software\\PhotoQt\\Capabilities" "ApplicationName" "PhotoQt Image Viewer"
WriteRegStr ShCtx "Software\\PhotoQt\\Capabilities" "ApplicationDescription" "Fast and highly configurable image viewer."
WriteRegStr ShCtx "Software\\PhotoQt\\Capabilities" "ApplicationIcon" "$INSTDIR\\files\\photoqt.exe,0"
"""

UN_FINAL_CONT = """;
; DO NOT EDIT THIS FILE!
; THIS FILE IS AUTO GENERATED BY RegisterCapabilities.py AND WILL
; LIKELY BE OVERWRITTEN AT SOME POINT!
;
SetRegView 64

DeleteRegValue ShCtx "Software\\RegisteredApplications" "PhotoQt"
DeleteRegKey ShCtx "Software\\PhotoQt"
"""

# this filters out the data from the plugin files
def getData(fname):

    # we don't want to register PhotoQt for these types
    if "_pdf" in fname or "_video" in fname:
        return ()

    f = open(f"../../cplusplus/images/plugins/{fname}")
    txt = f.read()

    ret = []

    # get the data structure
    if "magick" in fname:
        parts = txt.split("candidateData = {")[1].split(";")[0].split("}}},")
    else:
        parts = txt.split("setData(")[1].split(";")[0].split("}}},")

    # the perceived type based on plugin
    perceivedtype = "image"
    if "_pdf" in fname:
        perceivedtype = "document"
    elif "libarchive" in fname:
        perceivedtype = "compressed"
    elif "video" in fname:
        perceivedtype = "video"

    for p in parts:

        # these are additional data, not a format
        if p.count("{") < 4:
            continue

        # this filters out parts that are not important here
        splt = p.split("{{")[1].split("},")
        if len(splt) != 3:
            print(splt)

        # superfluous characters
        chars_to_remove = "'\"{}\n"

        # remove characters and split lists
        a = str.maketrans("", "", chars_to_remove)
        desc = splt[0].translate(a).strip()
        endg = splt[1].translate(a).split(",")
        mimt = splt[2].translate(a).split(",")

        # strip entries
        endg = [e.strip() for e in endg]
        mimt = [m.strip() for m in mimt]

        # no empty string entry only
        if len(mimt) == 1 and mimt[0] == "":
            mimt = []

        # already handled
        if endg[0] in recorded:
            continue
        recorded.extend(endg)

        # we don't register for archives except for comic books
        if perceivedtype == "compressed" and desc != "Comic book archive":
            continue

        # return data
        ret.append((desc, endg, mimt, ("document" if desc == "Comic book archive" else perceivedtype)))

    return ret

print("> Looping over all plugins and composing data...")

processed_endings = []

directory = os.fsencode("../../cplusplus/images/plugins/")
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".cpp"):

        dat = getData(filename)

        for line in dat:

            for endg in line[1]:

                if endg not in FORMATS_AVAILABLE:
                    print(f"THIS FORMAT IS NOT ENABLED: {endg}")
                    continue

                processed_endings.append(endg)

                FINAL_CONT += f"""
WriteRegStr ShCtx "Software\\PhotoQt\\Capabilities\\FileAssociations" ".{endg}" "photoqt.AssocFile.{endg.upper()}"
WriteRegStr ShCtx "Software\\Classes\\photoqt.AssocFile.{endg.upper()}" "" "{line[0]}"
WriteRegStr ShCtx "Software\\Classes\\photoqt.AssocFile.{endg.upper()}" "PerceivedType" "{line[3]}"
WriteRegStr ShCtx "Software\\Classes\\photoqt.AssocFile.{endg.upper()}\\DefaultIcon" "" "$INSTDIR\\filetypes\\{endg}.ico"
WriteRegStr ShCtx "Software\\Classes\\photoqt.AssocFile.{endg.upper()}\\shell\\open\\command" "" '"$INSTDIR\\files\\photoqt.exe" "%1"'
"""
                UN_FINAL_CONT += f"""DeleteRegKey ShCtx "Software\\Classes\\photoqt.AssocFile.{endg.upper()}"
"""

            for mimt in line[2]:
                FINAL_CONT += f"""WriteRegStr ShCtx "Software\\PhotoQt\\Capabilities\\MimeAssociations" ".{mimt}" "photoqt.AssocFile.{line[1][0].upper()}"
"""

        continue
    else:
        continue


for f in FORMATS_AVAILABLE:
    if f not in processed_endings:
        print(f"FORMAT {f} WAS NOT PROCESSED?")


print("> Writing data to RegisterCapabilities.nsh...")
with open("RegisterCapabilities.nsh", "w") as f:
    f.write(FINAL_CONT)

print("> Writing data to UnRegisterCapabilities.nsh...")
with open("UnRegisterCapabilities.nsh", "w") as f:
    f.write(UN_FINAL_CONT)

print("> Done!")
