#! /usr/bin/env bash

# make sure errors in sourced scripts will cause this script to stop
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

# needed for python environment to work
export PYTHONPATH="$this_dir/usr/conda/lib/python3.6"
export PYTHONHOME="$this_dir/usr/conda"

source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-qt-hook.sh"

exec "$this_dir"/AppRun.wrapped "$@"
